ALTER TABLE DYN_DW_PLAN3_FEEDBACK ADD TARGET_USER_ID VARCHAR2(50);
ALTER TABLE DYN_DW_PLAN3_FEEDBACK ADD TARGET_USER_NAME VARCHAR2(100);
ALTER TABLE DYN_DW_PLAN3_FEEDBACK ADD TARGET_PERSON_NODE_ID VARCHAR2(50);
