-- One-time import for 党委计划 3.0.
-- It copies old personnel-tree data into DYN_DW_PLAN3_PERSON_TREE and keeps runtime data isolated.

UPDATE DYN_DW_PLAN3_PERSON_TREE
   SET ENABLED = 'N',
       LAST_UPDATED_BY = 'DW_PLAN3_IMPORT',
       LAST_UPDATE_DATE = SYSDATE
 WHERE NVL(ENABLED, 'Y') = 'Y';

CREATE TABLE TMP_DW_PLAN3_PERSON_MAP AS
SELECT ID OLD_ID,
       RAWTOHEX(SYS_GUID()) NEW_ID
  FROM DYN_DW_PLAN_PERSON_TREE
 WHERE NVL(ENABLED, 'Y') = 'Y';

INSERT INTO DYN_DW_PLAN3_PERSON_TREE (
  ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_IP, VERSION, ORG_IDENTITY,
  PARENT_ID, NODE_NAME, USER_ID, USER_NAME, ROLE_CODE, SORT_NO, ENABLED, REMARK
)
SELECT m.NEW_ID,
       'DW_PLAN3_IMPORT',
       SYSDATE,
       'DW_PLAN3_IMPORT',
       SYSDATE,
       '127.0.0.1',
       0,
       NVL(o.ORG_IDENTITY, 'ORG_ROOT'),
       pm.NEW_ID,
       o.NODE_NAME,
       o.USER_ID,
       o.USER_NAME,
       o.ROLE_CODE,
       o.SORT_NO,
       NVL(o.ENABLED, 'Y'),
       o.REMARK
  FROM DYN_DW_PLAN_PERSON_TREE o
  JOIN TMP_DW_PLAN3_PERSON_MAP m ON m.OLD_ID = o.ID
  LEFT JOIN TMP_DW_PLAN3_PERSON_MAP pm ON pm.OLD_ID = o.PARENT_ID
 WHERE NVL(o.ENABLED, 'Y') = 'Y';

DROP TABLE TMP_DW_PLAN3_PERSON_MAP;
