ALTER TABLE DYN_DW_PLAN3_TASK ADD DRAFT_DEPT_NODE_ID VARCHAR2(50);
ALTER TABLE DYN_DW_PLAN3_TASK ADD DRAFT_DEPT_USER_ID VARCHAR2(50);
ALTER TABLE DYN_DW_PLAN3_TASK ADD DRAFT_DEPT_NAME VARCHAR2(200);

CREATE INDEX IDX_DW_PLAN3_TASK_DRAFT_DEPT ON DYN_DW_PLAN3_TASK (DRAFT_DEPT_NODE_ID);
