CREATE TABLE DYN_DW_PLAN3_BATCH (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  PLAN_YEAR NUMBER(4) NOT NULL,
  QUARTER VARCHAR2(20) NOT NULL,
  BATCH_NAME VARCHAR2(200),
  STATUS VARCHAR2(30),
  REMARK VARCHAR2(1000),
  CONSTRAINT PK_DYN_DW_PLAN3_BATCH PRIMARY KEY (ID)
);

CREATE TABLE DYN_DW_PLAN3_PERSON_TREE (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  PARENT_ID VARCHAR2(50),
  NODE_NAME VARCHAR2(200) NOT NULL,
  USER_ID VARCHAR2(50),
  USER_NAME VARCHAR2(100),
  ROLE_CODE VARCHAR2(30) NOT NULL,
  SORT_NO NUMBER(16),
  ENABLED VARCHAR2(10),
  REMARK VARCHAR2(1000),
  CONSTRAINT PK_DYN_DW_PLAN3_PERSON_TREE PRIMARY KEY (ID)
);

CREATE TABLE DYN_DW_PLAN3_TASK (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  BATCH_ID VARCHAR2(50),
  PARENT_ID VARCHAR2(50),
  ROOT_ID VARCHAR2(50),
  TASK_LEVEL VARCHAR2(30) NOT NULL,
  TITLE VARCHAR2(300) NOT NULL,
  CONTENT CLOB,
  TARGET_DESC VARCHAR2(2000),
  PLAN_DEADLINE DATE,
  STATUS VARCHAR2(30) NOT NULL,
  SENDER_ID VARCHAR2(50),
  SENDER_NAME VARCHAR2(100),
  RECEIVER_ID VARCHAR2(50),
  RECEIVER_NAME VARCHAR2(100),
  PERSON_NODE_ID VARCHAR2(50),
  ATTACHMENT_ID VARCHAR2(100),
  DISPATCH_TIME DATE,
  ACCEPT_TIME DATE,
  COMPLETE_TIME DATE,
  COMPLETE_DETAIL CLOB,
  RETURN_REASON VARCHAR2(1000),
  CONSTRAINT PK_DYN_DW_PLAN3_TASK PRIMARY KEY (ID)
);

CREATE TABLE DYN_DW_PLAN3_FEEDBACK (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  TASK_ID VARCHAR2(50) NOT NULL,
  FEEDBACK_USER_ID VARCHAR2(50),
  FEEDBACK_USER_NAME VARCHAR2(100),
  FEEDBACK_CONTENT CLOB,
  FEEDBACK_TIME DATE,
  ATTACHMENT_ID VARCHAR2(100),
  CONFIRM_USER_ID VARCHAR2(50),
  CONFIRM_USER_NAME VARCHAR2(100),
  CONFIRM_TIME DATE,
  CONFIRM_RESULT VARCHAR2(30),
  RETURN_REASON VARCHAR2(1000),
  CONSTRAINT PK_DYN_DW_PLAN3_FEEDBACK PRIMARY KEY (ID)
);

CREATE TABLE DYN_DW_PLAN3_ATTACHMENT (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  BUSINESS_ID VARCHAR2(50),
  BUSINESS_TYPE VARCHAR2(30),
  FILE_NAME VARCHAR2(500),
  CONTENT_TYPE VARCHAR2(200),
  FILE_SIZE NUMBER(16),
  FILE_CONTENT BLOB,
  CONSTRAINT PK_DYN_DW_PLAN3_ATTACHMENT PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_DW_PLAN3_BATCH_YQ ON DYN_DW_PLAN3_BATCH (PLAN_YEAR, QUARTER);
CREATE INDEX IDX_DW_PLAN3_PERSON_PARENT ON DYN_DW_PLAN3_PERSON_TREE (PARENT_ID);
CREATE INDEX IDX_DW_PLAN3_PERSON_USER ON DYN_DW_PLAN3_PERSON_TREE (USER_ID);
CREATE INDEX IDX_DW_PLAN3_TASK_PARENT ON DYN_DW_PLAN3_TASK (PARENT_ID);
CREATE INDEX IDX_DW_PLAN3_TASK_RECEIVER ON DYN_DW_PLAN3_TASK (RECEIVER_ID);
CREATE INDEX IDX_DW_PLAN3_TASK_SENDER ON DYN_DW_PLAN3_TASK (SENDER_ID);
CREATE INDEX IDX_DW_PLAN3_FEEDBACK_TASK ON DYN_DW_PLAN3_FEEDBACK (TASK_ID);
CREATE INDEX IDX_DW_PLAN3_ATTACH_BIZ ON DYN_DW_PLAN3_ATTACHMENT (BUSINESS_ID, BUSINESS_TYPE);


