DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1)
    INTO V_COUNT
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'DYN_DW_PLAN3_GRASSROOT_DISPATCH'
     AND COLUMN_NAME = 'TARGET_ORG_TYPE';

  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE DYN_DW_PLAN3_GRASSROOT_DISPATCH ADD TARGET_ORG_TYPE VARCHAR2(20)';
  END IF;
END;
/

UPDATE DYN_DW_PLAN3_GRASSROOT_DISPATCH
   SET TARGET_ORG_TYPE = CASE
       WHEN LOWER(NVL(BUSINESS_TYPE, 'd')) LIKE '%g%' OR BUSINESS_TYPE LIKE '%工会%' THEN 'g'
       WHEN LOWER(NVL(BUSINESS_TYPE, 'd')) LIKE '%t%' OR BUSINESS_TYPE LIKE '%团%' THEN 't'
       ELSE 'd'
   END
 WHERE TARGET_ORG_TYPE IS NULL;

COMMIT;
