CREATE TABLE DYN_DW_PLAN3_BATCH (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  PLAN_YEAR NUMBER(4) NOT NULL,
  QUARTER VARCHAR2(20) NOT NULL,
  BATCH_NAME VARCHAR2(200),
  STATUS VARCHAR2(30),
  REMARK VARCHAR2(1000),
  CONSTRAINT PK_DYN_DW_PLAN3_BATCH PRIMARY KEY (ID)
);

CREATE TABLE DYN_DW_PLAN3_PERSON_TREE (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  PARENT_ID VARCHAR2(50),
  NODE_NAME VARCHAR2(200) NOT NULL,
  USER_ID VARCHAR2(1000),
  USER_NAME VARCHAR2(1000),
  ROLE_CODE VARCHAR2(30) NOT NULL,
  SORT_NO NUMBER(16),
  ENABLED VARCHAR2(10),
  REMARK VARCHAR2(1000),
  CONSTRAINT PK_DYN_DW_PLAN3_PERSON_TREE PRIMARY KEY (ID)
);

CREATE TABLE DYN_DW_PLAN3_TASK (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  BATCH_ID VARCHAR2(50),
  PARENT_ID VARCHAR2(50),
  ROOT_ID VARCHAR2(50),
  TASK_LEVEL VARCHAR2(30) NOT NULL,
  TITLE VARCHAR2(300) NOT NULL,
  CONTENT CLOB,
  TARGET_DESC VARCHAR2(2000),
  PLAN_DEADLINE DATE,
  STATUS VARCHAR2(30) NOT NULL,
  SENDER_ID VARCHAR2(50),
  SENDER_NAME VARCHAR2(100),
  RECEIVER_ID VARCHAR2(50),
  RECEIVER_NAME VARCHAR2(100),
  PERSON_NODE_ID VARCHAR2(50),
  DRAFT_DEPT_NODE_ID VARCHAR2(50),
  DRAFT_DEPT_USER_ID VARCHAR2(50),
  DRAFT_DEPT_NAME VARCHAR2(200),
  ATTACHMENT_ID VARCHAR2(100),
  DISPATCH_TIME DATE,
  ACCEPT_TIME DATE,
  COMPLETE_TIME DATE,
  COMPLETE_DETAIL CLOB,
  RETURN_REASON VARCHAR2(1000),
  CONSTRAINT PK_DYN_DW_PLAN3_TASK PRIMARY KEY (ID)
);

CREATE TABLE DYN_DW_PLAN3_FEEDBACK (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  TASK_ID VARCHAR2(50) NOT NULL,
  FEEDBACK_USER_ID VARCHAR2(50),
  FEEDBACK_USER_NAME VARCHAR2(100),
  FEEDBACK_CONTENT CLOB,
  FEEDBACK_TIME DATE,
  ATTACHMENT_ID VARCHAR2(100),
  TARGET_USER_ID VARCHAR2(50),
  TARGET_USER_NAME VARCHAR2(100),
  TARGET_PERSON_NODE_ID VARCHAR2(50),
  CONFIRM_USER_ID VARCHAR2(50),
  CONFIRM_USER_NAME VARCHAR2(100),
  CONFIRM_TIME DATE,
  CONFIRM_RESULT VARCHAR2(30),
  RETURN_REASON VARCHAR2(1000),
  CONSTRAINT PK_DYN_DW_PLAN3_FEEDBACK PRIMARY KEY (ID)
);

CREATE TABLE DYN_DW_PLAN3_ATTACHMENT (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  BUSINESS_ID VARCHAR2(50),
  BUSINESS_TYPE VARCHAR2(30),
  FILE_NAME VARCHAR2(500),
  CONTENT_TYPE VARCHAR2(200),
  FILE_SIZE NUMBER(16),
  FILE_CONTENT BLOB,
  CONSTRAINT PK_DYN_DW_PLAN3_ATTACHMENT PRIMARY KEY (ID)
);

CREATE TABLE DYN_DW_PLAN3_GRASSROOT_DISPATCH (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  TASK_ID VARCHAR2(50) NOT NULL,
  BUSINESS_TREE_ID VARCHAR2(50) NOT NULL,
  BUSINESS_NAME VARCHAR2(500),
  BUSINESS_TYPE VARCHAR2(100),
  BUSINESS_CODE VARCHAR2(200),
  FORM_ID VARCHAR2(200),
  FORM_CODE VARCHAR2(200),
  VIEW_ID VARCHAR2(200),
  VIEW_CODE VARCHAR2(200),
  HAS_FORM VARCHAR2(50),
  COMPLETE_TYPE VARCHAR2(50),
  TARGET_ORG_TYPE VARCHAR2(20),
  PARTY_ORG_ID VARCHAR2(50) NOT NULL,
  PARTY_ORG_NAME VARCHAR2(500),
  PRINCIPAL_USER_ID VARCHAR2(50),
  RECEIVER_USER_ID VARCHAR2(50),
  PLAN_YEAR VARCHAR2(20),
  PLAN_MONTH VARCHAR2(20),
  PLAN_QUARTER VARCHAR2(20),
  DEADLINE DATE,
  REMARK VARCHAR2(1000),
  STATUS VARCHAR2(30),
  GRASSROOT_TASK_ID VARCHAR2(50),
  DISPATCH_TIME DATE,
  ERROR_MSG VARCHAR2(1000),
  CONSTRAINT PK_DW_PLAN3_GRASSROOT_DISPATCH PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_DW_PLAN3_BATCH_YQ ON DYN_DW_PLAN3_BATCH (PLAN_YEAR, QUARTER);
CREATE INDEX IDX_DW_PLAN3_PERSON_PARENT ON DYN_DW_PLAN3_PERSON_TREE (PARENT_ID);
CREATE INDEX IDX_DW_PLAN3_PERSON_USER ON DYN_DW_PLAN3_PERSON_TREE (USER_ID);
CREATE INDEX IDX_DW_PLAN3_TASK_PARENT ON DYN_DW_PLAN3_TASK (PARENT_ID);
CREATE INDEX IDX_DW_PLAN3_TASK_RECEIVER ON DYN_DW_PLAN3_TASK (RECEIVER_ID);
CREATE INDEX IDX_DW_PLAN3_TASK_SENDER ON DYN_DW_PLAN3_TASK (SENDER_ID);
CREATE INDEX IDX_DW_PLAN3_FEEDBACK_TASK ON DYN_DW_PLAN3_FEEDBACK (TASK_ID);
CREATE INDEX IDX_DW_PLAN3_ATTACH_BIZ ON DYN_DW_PLAN3_ATTACHMENT (BUSINESS_ID, BUSINESS_TYPE);
CREATE INDEX IDX_DW_PLAN3_GRASS_TASK ON DYN_DW_PLAN3_GRASSROOT_DISPATCH (TASK_ID);
CREATE INDEX IDX_DW_PLAN3_GRASS_TARGET ON DYN_DW_PLAN3_GRASSROOT_DISPATCH (BUSINESS_TREE_ID, TARGET_ORG_TYPE, PARTY_ORG_ID);


