-- 集团正式表同步：正式表结构以 FINEDB 截图为准。
-- 正式表不增加 PB 审计/同步字段；PB 元数据放在独立 DYN_* 表。

CREATE TABLE FINEDB.PULL_D12_PTY_MBR_BASIC_INFO (
  RYJBXX_GROUP_EMPLOYEE_COPE VARCHAR(8) NOT NULL,
  DY_COMPANY_NAME VARCHAR(50) NOT NULL,
  DY_PARTY_MEMBER_UNIQUE_ID VARCHAR(50) NOT NULL,
  DY_NAME VARCHAR(50) NOT NULL,
  DY_GENDER VARCHAR(50) NOT NULL,
  DY_ID_NUMBER CHAR(18) NOT NULL,
  DY_BIRTH_DATE DATE NOT NULL,
  DY_EDUCATION_LEVEL VARCHAR(50) NOT NULL,
  DY_DEGREE VARCHAR(50) NOT NULL,
  DY_ETHNICITY VARCHAR(50) NOT NULL,
  DY_JOB_POSITION VARCHAR(50) NOT NULL,
  DY_NEW_SOCIAL_STRATUM_TYPE VARCHAR(50) NOT NULL,
  DY_PROFESSIONAL_POSITION VARCHAR(50) NOT NULL,
  DY_IS_MIGRANT_WORKER CHAR(1) NOT NULL,
  DY_MOBILE_NUMBER VARCHAR(50) NOT NULL,
  DY_AFFILIATED_BRANCH VARCHAR(50) NOT NULL,
  DY_PARTY_ORGANIZATION_UNIQUE_ID VARCHAR(50) NOT NULL,
  DY_JOINT_BRANCH_UNIT VARCHAR(50),
  DY_HOUSEHOLD_LOCATION VARCHAR(50) NOT NULL,
  DY_CURRENT_ADDRESS VARCHAR(50) NOT NULL,
  DY_PARTY_ENTRY_DATE DATE NOT NULL,
  DY_PARTY_REGULARIZATION_DATE DATE NOT NULL,
  DY_PARTY_YEARS INTEGER NOT NULL,
  DY_PARTY_YEARS_CORRECTION INTEGER NOT NULL,
  DY_ENTRY_SYSTEM_TYPE VARCHAR(50) NOT NULL,
  DY_ENTRY_SYSTEM_DATE DATE NOT NULL,
  DY_ENTRY_SYSTEM_OPERATING_PARTY_ID VARCHAR(50) NOT NULL,
  DY_EXIT_SYSTEM_TYPE VARCHAR(50) NOT NULL,
  DY_EXIT_SYSTEM_DATE DATE NOT NULL,
  DY_EXIT_SYSTEM_OPERATING_PARTY_ID VARCHAR(50) NOT NULL,
  DY_UPDATE_TIMESTAMP DATETIME(6) NOT NULL,
  DY_OPERATING_PARTY_ORGANIZATION VARCHAR(50) NOT NULL,
  CONSTRAINT PK_PULL_D12_PTY_MBR_BASIC_INFO PRIMARY KEY (RYJBXX_GROUP_EMPLOYEE_COPE)
);

CREATE TABLE FINEDB.PULL_D12_PTY_ORG_BASIC_INFO (
  DZZ_PARTY_ORGANIZATION_UNIQUE_ID VARCHAR(32) NOT NULL,
  DZZ_COMPANY_NAME VARCHAR(50) NOT NULL,
  DZZ_UPPER_PARTY_ORGANIZATION_UNIQUE_ID VARCHAR(32) NOT NULL,
  DZZ_PARTY_ORGANIZATION_ENCODING VARCHAR(12) NOT NULL,
  DZZ_PARTY_ORGANIZATION_FULL_NAME VARCHAR(50) NOT NULL,
  DZZ_PARTY_ORGANIZATION_SHORT_NAME VARCHAR(50) NOT NULL,
  DZZ_PARTY_ORGANIZATION_CATEGORY VARCHAR(50) NOT NULL,
  DZZ_PARTY_ORGANIZATION_ESTABLISHMENT_DATE DATE NOT NULL,
  DZZ_PARTY_ORGANIZATION_MEMBER_COUNT INTEGER NOT NULL,
  DZZ_PARTY_ORGANIZATION_CONTACT_EMPLOYEE_CODE CHAR(10) NOT NULL,
  DZZ_PARTY_ORGANIZATION_CONTACT_NAME VARCHAR(50) NOT NULL,
  DZZ_PARTY_ORGANIZATION_CONTACT_MOBILE VARCHAR(50) NOT NULL,
  DZZ_PARTY_ORGANIZATION_UNIT_SITUATION VARCHAR(50) NOT NULL,
  DZZ_PARTY_ORGANIZATION_ADMINISTRATIVE_AREA VARCHAR(50) NOT NULL,
  DZZ_DISPLAY_ORDER INTEGER NOT NULL,
  DZZ_UPPER_PARTY_ORGANIZATION_FULL_NAME VARCHAR(50) NOT NULL,
  DZZ_DELETE_FLAG CHAR(1) NOT NULL,
  DZZ_UPDATE_TIMESTAMP DATETIME(6),
  DZZ_PARTY_BRANCH_STANDARDIZATION_CATEGORY VARCHAR(50),
  DZZ_OPERATING_PARTY_ORGANIZATION VARCHAR(50),
  CONSTRAINT PK_PULL_D12_PTY_ORG_BASIC_INFO PRIMARY KEY (DZZ_PARTY_ORGANIZATION_UNIQUE_ID)
);

CREATE TABLE DYN_GROUP_SYNC_ID_MAP (
  ID VARCHAR2(50), CREATED_BY VARCHAR2(50), CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50), LAST_UPDATE_DATE DATE, LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16), ORG_IDENTITY VARCHAR2(32),
  SOURCE_TABLE VARCHAR2(50) NOT NULL, SOURCE_ID VARCHAR2(100) NOT NULL,
  TARGET_TABLE VARCHAR2(100) NOT NULL, TARGET_KEY VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_DYN_GROUP_SYNC_ID_MAP PRIMARY KEY (ID),
  CONSTRAINT UK_DYN_GROUP_SYNC_ID_MAP UNIQUE (ORG_IDENTITY, SOURCE_TABLE, SOURCE_ID)
);

CREATE TABLE DYN_GROUP_SYNC_REJECT (
  ID VARCHAR2(50), CREATED_BY VARCHAR2(50), CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50), LAST_UPDATE_DATE DATE, LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16), ORG_IDENTITY VARCHAR2(32),
  BATCH_ID VARCHAR2(50) NOT NULL, SOURCE_TABLE VARCHAR2(50) NOT NULL,
  SOURCE_ID VARCHAR2(100), REASON_CODE VARCHAR2(50) NOT NULL,
  DETAIL_MESSAGE VARCHAR2(4000) NOT NULL,
  CONSTRAINT PK_DYN_GROUP_SYNC_REJECT PRIMARY KEY (ID)
);

CREATE TABLE DYN_GROUP_SYNC_LOG (
  ID VARCHAR2(50), CREATED_BY VARCHAR2(50), CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50), LAST_UPDATE_DATE DATE, LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16), ORG_IDENTITY VARCHAR2(32),
  BATCH_START_TIME DATE, BATCH_END_TIME DATE, STATUS VARCHAR2(20),
  TOTAL_COUNT NUMBER(10), SUCCESS_COUNT NUMBER(10), ERROR_COUNT NUMBER(10),
  DELETED_COUNT NUMBER(10), TRIGGER_TYPE VARCHAR2(20), EXECUTOR_ID VARCHAR2(100),
  CALL_IP VARCHAR2(50), INCREMENTAL_FROM DATE, ERROR_MESSAGE CLOB,
  CONSTRAINT PK_DYN_GROUP_SYNC_LOG PRIMARY KEY (ID)
);

CREATE INDEX IDX_DYN_GROUP_SYNC_REJECT_BATCH ON DYN_GROUP_SYNC_REJECT (ORG_IDENTITY, BATCH_ID);
CREATE INDEX IDX_DYN_GROUP_SYNC_LOG_TIME ON DYN_GROUP_SYNC_LOG (ORG_IDENTITY, BATCH_START_TIME DESC);

COMMENT ON TABLE FINEDB.PULL_D12_PTY_MBR_BASIC_INFO IS '党员基本信息';
COMMENT ON TABLE FINEDB.PULL_D12_PTY_ORG_BASIC_INFO IS '党组织基本信息';
COMMENT ON COLUMN FINEDB.PULL_D12_PTY_MBR_BASIC_INFO.RYJBXX_GROUP_EMPLOYEE_COPE IS '集团员工编码';
COMMENT ON COLUMN FINEDB.PULL_D12_PTY_ORG_BASIC_INFO.DZZ_PARTY_ORGANIZATION_UNIQUE_ID IS '党组织唯一标识';
