CREATE TABLE DYN_GROUP_SYNC_OVERRIDE (
  ID VARCHAR2(50), CREATED_BY VARCHAR2(50), CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50), LAST_UPDATE_DATE DATE, LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16), ORG_IDENTITY VARCHAR2(32), TARGET_TYPE VARCHAR2(20) NOT NULL,
  TARGET_ID VARCHAR2(50) NOT NULL, FIELD_NAME VARCHAR2(100) NOT NULL,
  FIELD_VALUE VARCHAR2(2000), IMPORT_BATCH_ID VARCHAR2(50), ACTIVE_FLAG CHAR(1),
  CONSTRAINT PK_DYN_GROUP_SYNC_OVERRIDE PRIMARY KEY (ID),
  CONSTRAINT UK_DYN_GROUP_SYNC_OVERRIDE UNIQUE (ORG_IDENTITY, TARGET_TYPE, TARGET_ID, FIELD_NAME)
);
COMMENT ON TABLE DYN_GROUP_SYNC_OVERRIDE IS '同步集团数据-Excel导入字段覆盖值';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.ID IS '主键';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.CREATED_BY IS '创建人';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.CREATION_DATE IS '创建时间';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.LAST_UPDATED_BY IS '最后更新人';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.LAST_UPDATE_DATE IS '最后更新时间';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.LAST_UPDATE_IP IS '最后更新IP';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.VERSION IS '版本号';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.ORG_IDENTITY IS '组织身份';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.TARGET_TYPE IS '目标类型';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.TARGET_ID IS '目标记录ID';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.FIELD_NAME IS '被覆盖字段名';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.FIELD_VALUE IS '覆盖值';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.IMPORT_BATCH_ID IS '导入批次ID';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.ACTIVE_FLAG IS '有效标识';
CREATE INDEX IDX_GROUP_SYNC_OVERRIDE_TARGET ON DYN_GROUP_SYNC_OVERRIDE (ORG_IDENTITY, TARGET_TYPE, TARGET_ID);
