-- 升级路径（人工执行，先备份/核对，默认不自动删除旧表）。
-- 1. 备份同步日志和元数据表。
-- CREATE TABLE DYN_GROUP_SYNC_LOG_BAK_YYYYMMDD AS SELECT * FROM DYN_GROUP_SYNC_LOG;
-- 2. 执行 group_data_sync.sql，核对正式表字段/主键。
-- 3. 执行正式同步并完成重复、拒绝、删除保护验收后，人工下线旧表：
-- 回滚：停止正式同步，恢复备份表名称；正式表不删除，保留供审计。
