-- 同步集团数据：集团党员、党组织标准表及内部同步日志
-- 目标数据库：达梦/Oracle 兼容语法

CREATE TABLE DYN_DY_PARTY_MEMBER (
  ID VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  DY_JBXX_GROUP_EMPLOYEE_CODE NUMBER(8),
  DY_COMPANY_NAME VARCHAR2(500),
  DY_PARTY_MEMBER_UNIQUE_ID VARCHAR2(100) NOT NULL,
  DY_NAME VARCHAR2(200),
  DY_GENDER VARCHAR2(100),
  DY_ID_NUMBER CHAR(18),
  DY_BIRTH_DATE DATE,
  DY_EDUCATION_LEVEL VARCHAR2(100),
  DY_DEGREE VARCHAR2(100),
  DY_ETHNICITY VARCHAR2(100),
  DY_JOB_POSITION VARCHAR2(500),
  DY_NEW_SOCIAL_STRATUM_TYPE VARCHAR2(200),
  DY_PROFESSIONAL_POSITION VARCHAR2(500),
  DY_IS_MIGRANT_WORKER CHAR(1),
  DY_MOBILE_NUMBER VARCHAR2(100),
  DY_AFFILIATED_BRANCH VARCHAR2(500),
  DY_PARTY_ORGANIZATION_UNIQUE_ID VARCHAR2(100),
  DY_JOINT_BRANCH_UNIT VARCHAR2(500),
  DY_HOUSEHOLD_LOCATION VARCHAR2(500),
  DY_CURRENT_ADDRESS VARCHAR2(1000),
  DY_PARTY_ENTRY_DATE DATE,
  DY_PARTY_REGULARIZATION_DATE DATE,
  DY_PARTY_YEARS NUMBER(3),
  DY_PARTY_YEARS_CORRECTION NUMBER(4),
  DY_ENTRY_SYSTEM_TYPE VARCHAR2(200),
  DY_ENTRY_SYSTEM_DATE DATE,
  DY_ENTRY_SYSTEM_OPERATING_PARTY_ID VARCHAR2(100),
  DY_EXIT_SYSTEM_TYPE VARCHAR2(200),
  DY_EXIT_SYSTEM_DATE DATE,
  DY_EXIT_SYSTEM_OPERATING_PARTY_ID VARCHAR2(100),
  DY_DELETE_FLAG CHAR(1),
  DY_UPDATE_TIMESTAMP DATE,
  DY_OPERATING_PARTY_ORGANIZATION VARCHAR2(200),
  SYNC_SOURCE_ID VARCHAR2(100),
  SYNC_SOURCE_TABLE VARCHAR2(100),
  SYNC_BATCH_ID VARCHAR2(100),
  SYNC_STATE VARCHAR2(20),
  SYNC_ERROR_MESSAGE VARCHAR2(4000),
  CONSTRAINT PK_DYN_DY_PARTY_MEMBER PRIMARY KEY (ID),
  CONSTRAINT UK_DYN_DY_PARTY_MEMBER_UID UNIQUE (DY_PARTY_MEMBER_UNIQUE_ID)
);

CREATE TABLE DYN_DZZ_PARTY_ORGANIZATION (
  ID VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  DZZ_PARTY_ORGANIZATION_UNIQUE_ID VARCHAR2(100) NOT NULL,
  DZZ_COMPANY_NAME VARCHAR2(500),
  DZZ_UPPER_PARTY_ORGANIZATION_UNIQUE_ID VARCHAR2(100),
  DZZ_PARTY_ORGANIZATION_ENCODING VARCHAR2(100),
  DZZ_PARTY_ORGANIZATION_FULL_NAME VARCHAR2(500),
  DZZ_PARTY_ORGANIZATION_SHORT_NAME VARCHAR2(500),
  DZZ_PARTY_ORGANIZATION_CATEGORY VARCHAR2(200),
  DZZ_PARTY_ORGANIZATION_ESTABLISHMENT_DATE DATE,
  DZZ_PARTY_ORGANIZATION_MEMBER_COUNT NUMBER(4),
  DZZ_PARTY_ORGANIZATION_CONTACT_EMPLOYEE_CODE VARCHAR2(50),
  DZZ_PARTY_ORGANIZATION_CONTACT_NAME VARCHAR2(200),
  DZZ_PARTY_ORGANIZATION_CONTACT_MOBILE VARCHAR2(100),
  DZZ_PARTY_ORGANIZATION_UNIT_SITUATION VARCHAR2(500),
  DZZ_PARTY_ORGANIZATION_ADMINISTRATIVE_AREA VARCHAR2(500),
  DZZ_DISPLAY_ORDER NUMBER(10),
  DZZ_UPPER_PARTY_ORGANIZATION_FULL_NAME VARCHAR2(500),
  DZZ_DELETE_FLAG CHAR(1),
  DZZ_UPDATE_TIMESTAMP DATE,
  DZZ_PARTY_BRANCH_STANDARDIZATION_CATEGORY VARCHAR2(200),
  DZZ_OPERATING_PARTY_ORGANIZATION VARCHAR2(200),
  DZZ_PARTY_ORGANIZATION_SECRETARY_NAME VARCHAR2(200),
  DZZ_PARTY_ORGANIZATION_DEPUTY_SECRETARY_NAME VARCHAR2(200),
  SYNC_SOURCE_ID VARCHAR2(100),
  SYNC_SOURCE_TABLE VARCHAR2(100),
  SYNC_BATCH_ID VARCHAR2(100),
  SYNC_STATE VARCHAR2(20),
  SYNC_ERROR_MESSAGE VARCHAR2(4000),
  CONSTRAINT PK_DYN_DZZ_PARTY_ORGANIZATION PRIMARY KEY (ID),
  CONSTRAINT UK_DYN_DZZ_PARTY_ORG_UID UNIQUE (DZZ_PARTY_ORGANIZATION_UNIQUE_ID)
);

COMMENT ON TABLE DYN_DY_PARTY_MEMBER IS '同步集团数据-集团党员基本信息表';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.ID IS '主键';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.CREATED_BY IS '创建人';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.CREATION_DATE IS '创建时间';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.LAST_UPDATED_BY IS '最后更新人';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.LAST_UPDATE_DATE IS '最后更新时间';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.LAST_UPDATE_IP IS '最后更新IP';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.VERSION IS '版本号';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.ORG_IDENTITY IS '组织身份';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_JBXX_GROUP_EMPLOYEE_CODE IS '集团员工编码';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_COMPANY_NAME IS '企业名称';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_PARTY_MEMBER_UNIQUE_ID IS '集团党员唯一标识';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_NAME IS '姓名';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_GENDER IS '性别';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_ID_NUMBER IS '公民身份号码';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_BIRTH_DATE IS '出生日期';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_EDUCATION_LEVEL IS '学历';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_DEGREE IS '学位';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_ETHNICITY IS '民族';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_JOB_POSITION IS '工作岗位';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_NEW_SOCIAL_STRATUM_TYPE IS '新社会阶层类型';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_PROFESSIONAL_POSITION IS '专业技术职务';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_IS_MIGRANT_WORKER IS '是否农民工';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_MOBILE_NUMBER IS '手机号码';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_AFFILIATED_BRANCH IS '组织关系所在党支部';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_PARTY_ORGANIZATION_UNIQUE_ID IS '党组织唯一标识';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_JOINT_BRANCH_UNIT IS '联合支部所在单位';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_HOUSEHOLD_LOCATION IS '户籍所在地';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_CURRENT_ADDRESS IS '现居住地';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_PARTY_ENTRY_DATE IS '入党日期';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_PARTY_REGULARIZATION_DATE IS '转正日期';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_PARTY_YEARS IS '党龄';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_PARTY_YEARS_CORRECTION IS '党龄校正值（月）';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_ENTRY_SYSTEM_TYPE IS '进入本系统类型';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_ENTRY_SYSTEM_DATE IS '进入本系统日期';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_ENTRY_SYSTEM_OPERATING_PARTY_ID IS '进入本系统操作党组织唯一标识';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_EXIT_SYSTEM_TYPE IS '离开本系统类型';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_EXIT_SYSTEM_DATE IS '离开本系统日期';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_EXIT_SYSTEM_OPERATING_PARTY_ID IS '离开本系统操作党组织唯一标识';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_DELETE_FLAG IS '删除标识';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_UPDATE_TIMESTAMP IS '源数据更新时间';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.DY_OPERATING_PARTY_ORGANIZATION IS '操作党组织';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.SYNC_SOURCE_ID IS '源表记录ID';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.SYNC_SOURCE_TABLE IS '源表名称';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.SYNC_BATCH_ID IS '同步批次ID';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.SYNC_STATE IS '同步状态';
COMMENT ON COLUMN DYN_DY_PARTY_MEMBER.SYNC_ERROR_MESSAGE IS '同步异常信息';

COMMENT ON TABLE DYN_DZZ_PARTY_ORGANIZATION IS '同步集团数据-集团党组织基本信息表';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.ID IS '主键';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.CREATED_BY IS '创建人';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.CREATION_DATE IS '创建时间';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.LAST_UPDATED_BY IS '最后更新人';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.LAST_UPDATE_DATE IS '最后更新时间';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.LAST_UPDATE_IP IS '最后更新IP';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.VERSION IS '版本号';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.ORG_IDENTITY IS '组织身份';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_UNIQUE_ID IS '集团党组织唯一标识';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_COMPANY_NAME IS '企业名称';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_UPPER_PARTY_ORGANIZATION_UNIQUE_ID IS '上级党组织唯一标识';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_ENCODING IS '党组织编码';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_FULL_NAME IS '党组织全称';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_SHORT_NAME IS '党组织简称';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_CATEGORY IS '组织类别';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_ESTABLISHMENT_DATE IS '成立日期';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_MEMBER_COUNT IS '党员人数';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_CONTACT_EMPLOYEE_CODE IS '联系人员工编码';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_CONTACT_NAME IS '联系人姓名';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_CONTACT_MOBILE IS '联系人手机号';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_UNIT_SITUATION IS '党组织所在单位情况';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_ADMINISTRATIVE_AREA IS '所在行政区划';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_DISPLAY_ORDER IS '显示顺序';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_UPPER_PARTY_ORGANIZATION_FULL_NAME IS '上级党组织全称';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_DELETE_FLAG IS '删除标识';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_UPDATE_TIMESTAMP IS '源数据更新时间';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_BRANCH_STANDARDIZATION_CATEGORY IS '党支部标准化规范化建设类别';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_OPERATING_PARTY_ORGANIZATION IS '操作党组织';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_SECRETARY_NAME IS '党组织书记姓名';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.DZZ_PARTY_ORGANIZATION_DEPUTY_SECRETARY_NAME IS '党组织副书记姓名';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.SYNC_SOURCE_ID IS '源表记录ID';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.SYNC_SOURCE_TABLE IS '源表名称';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.SYNC_BATCH_ID IS '同步批次ID';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.SYNC_STATE IS '同步状态';
COMMENT ON COLUMN DYN_DZZ_PARTY_ORGANIZATION.SYNC_ERROR_MESSAGE IS '同步异常信息';

CREATE TABLE DYN_GROUP_SYNC_LOG (
  ID VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  BATCH_START_TIME DATE,
  BATCH_END_TIME DATE,
  STATUS VARCHAR2(20),
  TOTAL_COUNT NUMBER(10),
  SUCCESS_COUNT NUMBER(10),
  ERROR_COUNT NUMBER(10),
  DELETED_COUNT NUMBER(10),
  TRIGGER_TYPE VARCHAR2(20),
  EXECUTOR_ID VARCHAR2(100),
  ERROR_MESSAGE CLOB,
  CONSTRAINT PK_DYN_GROUP_SYNC_LOG PRIMARY KEY (ID)
);

CREATE INDEX IDX_DY_PARTY_MEMBER_SOURCE ON DYN_DY_PARTY_MEMBER (SYNC_SOURCE_TABLE, SYNC_SOURCE_ID);
CREATE INDEX IDX_DY_PARTY_MEMBER_ORG ON DYN_DY_PARTY_MEMBER (ORG_IDENTITY, DY_DELETE_FLAG);
CREATE INDEX IDX_DZZ_PARTY_ORG_SOURCE ON DYN_DZZ_PARTY_ORGANIZATION (SYNC_SOURCE_TABLE, SYNC_SOURCE_ID);
CREATE INDEX IDX_DZZ_PARTY_ORG_PARENT ON DYN_DZZ_PARTY_ORGANIZATION (DZZ_UPPER_PARTY_ORGANIZATION_UNIQUE_ID);
CREATE INDEX IDX_GROUP_SYNC_LOG_TIME ON DYN_GROUP_SYNC_LOG (ORG_IDENTITY, BATCH_START_TIME DESC);

CREATE TABLE DYN_GROUP_SYNC_OVERRIDE (
  ID VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  TARGET_TYPE VARCHAR2(50) NOT NULL,
  TARGET_ID VARCHAR2(100) NOT NULL,
  FIELD_NAME VARCHAR2(200) NOT NULL,
  FIELD_VALUE VARCHAR2(4000),
  IMPORT_BATCH_ID VARCHAR2(100),
  ACTIVE_FLAG CHAR(1),
  CONSTRAINT PK_DYN_GROUP_SYNC_OVERRIDE PRIMARY KEY (ID),
  CONSTRAINT UK_DYN_GROUP_SYNC_OVERRIDE UNIQUE (ORG_IDENTITY, TARGET_TYPE, TARGET_ID, FIELD_NAME)
);

COMMENT ON TABLE DYN_GROUP_SYNC_OVERRIDE IS '同步集团数据-Excel导入字段覆盖值';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.ID IS '主键';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.CREATED_BY IS '创建人';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.CREATION_DATE IS '创建时间';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.LAST_UPDATED_BY IS '最后更新人';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.LAST_UPDATE_DATE IS '最后更新时间';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.LAST_UPDATE_IP IS '最后更新IP';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.VERSION IS '版本号';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.ORG_IDENTITY IS '组织身份';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.TARGET_TYPE IS '目标类型';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.TARGET_ID IS '目标记录ID';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.FIELD_NAME IS '被覆盖字段名';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.FIELD_VALUE IS '覆盖值';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.IMPORT_BATCH_ID IS '导入批次ID';
COMMENT ON COLUMN DYN_GROUP_SYNC_OVERRIDE.ACTIVE_FLAG IS '有效标识';

CREATE INDEX IDX_GROUP_SYNC_OVERRIDE_TARGET ON DYN_GROUP_SYNC_OVERRIDE (ORG_IDENTITY, TARGET_TYPE, TARGET_ID);
