CREATE TABLE PB_PORTAL_BUSINESS_TODO (
  ID VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  SOURCE_MODULE VARCHAR2(100) NOT NULL,
  BUSINESS_ID VARCHAR2(50) NOT NULL,
  BUSINESS_SCENE VARCHAR2(50) NOT NULL,
  RECEIVER_ID VARCHAR2(50) NOT NULL,
  RECEIVER_NAME VARCHAR2(100),
  TITLE VARCHAR2(500) NOT NULL,
  TASK_TYPE VARCHAR2(100),
  TASK_DESC VARCHAR2(2000),
  TODO_STATUS VARCHAR2(30) NOT NULL,
  PRIORITY VARCHAR2(10),
  SEND_USER_ID VARCHAR2(50),
  SEND_USER_NAME VARCHAR2(100),
  SEND_TIME TIMESTAMP,
  TARGET_URL VARCHAR2(1000),
  CLOSE_TIME DATE,
  CLOSE_REASON VARCHAR2(500),
  CONSTRAINT PK_PB_PORTAL_BUSINESS_TODO PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_PB_PORTAL_BIZ_TODO ON PB_PORTAL_BUSINESS_TODO (
  SOURCE_MODULE,
  BUSINESS_ID,
  BUSINESS_SCENE,
  RECEIVER_ID
);

CREATE INDEX IDX_PB_PORTAL_BIZ_TODO_USER ON PB_PORTAL_BUSINESS_TODO (
  RECEIVER_ID,
  TODO_STATUS,
  SEND_TIME
);

CREATE INDEX IDX_PB_PORTAL_BIZ_TODO_BIZ ON PB_PORTAL_BUSINESS_TODO (
  SOURCE_MODULE,
  BUSINESS_ID,
  TODO_STATUS
);
