platform.portal.url=http://daportal.da.net/pb/login/login_da_cas.jsp?sourceURI=/pb/
platform.portal.todo.username=portal
platform.portal.todo.password=portal
platform.portal.todo.casenable=false
platform.portal.todo.hidden.secret=