create table PB_EXCEL_EXPORT_CONFIG (
  ID VARCHAR2(50) not null,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  CONFIG_CODE VARCHAR2(100) not null,
  CONFIG_NAME VARCHAR2(200) not null,
  CONFIG_TYPE VARCHAR2(20) not null,
  TABLE_NAME VARCHAR2(100) not null,
  TABLE_COMMENT VARCHAR2(500),
  STATUS VARCHAR2(10),
  REMARK VARCHAR2(1000),
  primary key (ID)
);

create unique index UK_PB_EXCEL_EXPORT_CONFIG on PB_EXCEL_EXPORT_CONFIG(CONFIG_CODE);

create table PB_EXCEL_EXPORT_COLUMN (
  ID VARCHAR2(50) not null,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  CONFIG_ID VARCHAR2(50) not null,
  TABLE_NAME VARCHAR2(100),
  COLUMN_NAME VARCHAR2(100) not null,
  COLUMN_LABEL VARCHAR2(200),
  COLUMN_TYPE VARCHAR2(100),
  COLUMN_LENGTH NUMBER(16),
  EXPORT_FLAG VARCHAR2(10),
  SORT_NO NUMBER(16),
  COLUMN_WIDTH NUMBER(16),
  primary key (ID)
);

create index IDX_PB_EXCEL_COLUMN_CFG on PB_EXCEL_EXPORT_COLUMN(CONFIG_ID, SORT_NO);

create table PB_EXCEL_EXPORT_RELATION (
  ID VARCHAR2(50) not null,
  CREATED_BY VARCHAR2(50),
  CREATION_DATE DATE,
  LAST_UPDATED_BY VARCHAR2(50),
  LAST_UPDATE_DATE DATE,
  LAST_UPDATE_IP VARCHAR2(50),
  VERSION NUMBER(16),
  ORG_IDENTITY VARCHAR2(32),
  MAIN_CONFIG_ID VARCHAR2(50) not null,
  CHILD_CONFIG_ID VARCHAR2(50) not null,
  MAIN_COLUMN_NAME VARCHAR2(100) not null,
  CHILD_COLUMN_NAME VARCHAR2(100) not null,
  SORT_NO NUMBER(16),
  primary key (ID)
);

create index IDX_PB_EXCEL_REL_MAIN on PB_EXCEL_EXPORT_RELATION(MAIN_CONFIG_ID, SORT_NO);
